//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfort.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComfortEntities : DbContext
    {
        public ComfortEntities()
            : base("name=ComfortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DiscountPartners> DiscountPartners { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<FamilyStatus> FamilyStatus { get; set; }
        public DbSet<Health> Health { get; set; }
        public DbSet<Logins> Logins { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ProductsMaterial> ProductsMaterial { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<ProductWorkshop> ProductWorkshop { get; set; }
        public DbSet<Request> Request { get; set; }
        public DbSet<RequestDetails> RequestDetails { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SaleHistory> SaleHistory { get; set; }
        public DbSet<SalePoint> SalePoint { get; set; }
        public DbSet<SizeUpakovka> SizeUpakovka { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeMaterial> TypeMaterial { get; set; }
        public DbSet<TypeOfBusiness> TypeOfBusiness { get; set; }
        public DbSet<TypeWorkshop> TypeWorkshop { get; set; }
        public DbSet<Workshop> Workshop { get; set; }
    }
}
